### ISSUE TITLE
more samples and demos, please!

### ISSUE THREAD

**Issue by xaota** [andykorth/Pencil.Gaming#37]
LoadModel with textures, Lights, Shaders, Blendings, DrawText, Audio, Controllers, etc

**Comment by migueltk** [comment]
You can find a sample application [here](https://sites.google.com/site/bitiopia/nanovg-fontstash), I hope you will help.

regards

**Comment by fin-ger** [comment]
As Pencil.Gaming is an OpenGL binding for c# you can use any OpenGL Tutorial for reference. If you would like to have a working application written with Pencil.Gaming have a look at https://github.com/AreonDev/NoWayOut

This is a game with a small "game engine" (not finished yet) that uses a Pencil.Gaming based renderer, with OpenAL for sound, jitterphysics as a physics engine and GWEN.NET for UI rendering. The renderer can only load objs for now (no animation of meshes) and uses deferred shading for lighting. The entities management is build on top of a concept called Entity-Component-System. You can Google for it to understand how we integrated all the libraries into Pencil.Gaming. Don't be confused by our Postprocessor. The Postprocessor analyzes a compiled .net binary and checks if our ECS was used correctly. This is a bit tricky... 
The engine is currently not under active development but will possibly be in the future.

**Comment by antonijn** [comment]
GLFW has its own examples and docs, as do OpenGL and OpenAL. There are specific examples on the Pencil.Gaming GitHub wiki.
