### ISSUE TITLE
Window creation comparison operator

### ISSUE THREAD

**Issue by Wargog** [andykorth/Pencil.Gaming#38]
When creating a new window, if you error check it, you will get an operator `==` error, and you cannot use `if (window == GlfwWindowPtr.Null) {` to check for errors in window creation

**Comment by bbrown683** [comment]
Seems like a possible oversight. I guess it wasn't that large of a deal since you can use workarounds such as `if(window.Equals(null))` or `if(window == IntPtr.Zero)` that do pretty much the same thing.
