### ISSUE TITLE
DllNotFoundException when starting in an another path.

### ISSUE THREAD

**Issue by TSnake41** [andykorth/Pencil.Gaming#41]
Hello, when run using an another path (like user path) makes the library crash because it can't find the natives libs.

`System.DllNotFoundException: natives64/libglfw.so
  at (wrapper managed-to-native) Pencil.Gaming.Glfw64:glfwInit ()
  at Pencil.Gaming.Glfw.Init () <0x415b5320 + 0x0001d> in <filename unknown>:0 
  at Program.Main () <0x4159efd0 + 0x0005f> in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: natives64/libglfw.so
  at (wrapper managed-to-native) Pencil.Gaming.Glfw64:glfwInit ()
  at Pencil.Gaming.Glfw.Init () <0x415b5320 + 0x0001d> in <filename unknown>:0 
  at Program.Main () <0x4159efd0 + 0x0005f> in <filename unknown>:0`

**Comment by andykorth** [comment]
Yeah, I think this just a general mono issue, and probably nothing can be done specifically with Pencil.Gaming to fix it. Are you having this on Mac, Linux, Windows, etc? 

There's a bit of information that may be helpful here: http://www.mono-project.com/docs/advanced/pinvoke/dllnotfoundexception/

There's also the Pencil.Gaming.dll.config file.

Maybe you'll be able to set the LD_LIBRARY_PATH before launching the app and that will fix your issue.

```
export LD_LIBRARY_PATH=/path/to/dylib:$LD_LIBRARY_PATH
mono yourprogram.exe
```

**Comment by TSnake41** [comment]
Thanks you for your reply.

This problem append on Windows and Linux (using "run with" of the file manager).

I have found a workaround by defining the current directory to the directory of the executable before using Pencil.Gaming.
`Environment.CurrentDirectory = Path.GetDirectoryName(typeof(Program).Assembly.Location);`

**Comment by andykorth** [comment]
That's pretty neat. It's probably valuable for other resource loading that your app will do. That's probably worth adding to the main README. Thanks!

**Comment by WolfGaming** [comment]
I am currently experiencing this problem when running your package in MonoDevelop.
No matter if I copy the natives to the output directory, or add them to the project it just doesnt want to run for me.

Any idea why?
