### ISSUE TITLE
glBindImageTexture not implemented

### ISSUE THREAD

**Issue by courgeon** [andykorth/Pencil.Gaming#43]
Hello, First, thanks for the awesome work. I'm switching from LWJGL / java to C# using your Pencil Gaming lib, it's great ! 

However, i'm using OpenGL 4.2 compute shaders, and I can't find any wrapping of the function :
`glBindImageTexture `

https://www.opengl.org/sdk/docs/man/html/glBindImageTexture.xhtml

Would you add it ? otherwise compute shaders are pretty useless.

Thanks

**Comment by courgeon** [comment]
Ok, neverming, I finally figured out how to add it by myself. :)

**Comment by andykorth** [comment]
Awesome. I think we don't have any OpenGL 4 bindings. Pencil.Gaming does use a stripped down set of OpenGL bindings compared to the OpenTK bindings. OpenTK had a pretty complicated system for switching between different OpenGL versions, GL ES, various sets of extensions.. Pencil.Gaming avoids that complexity so I haven't really thought about adding OpenGL 4 stuff.

**Comment by courgeon** [comment]
Well, from what i've seen, At least Compute Shaders related bindings are all there (except for the mentioned one) I've now fully converted my 3d engine and plugged in BulletSharp (in place of JBullet) and everything is working seamlessly. For now I've everything i need. Good job !

**Comment by courgeon** [comment]
FYI, I just updloaded a first glimpse of my C# converted engine here :
https://youtu.be/w5_chYhwyMQ
It runs upon Pencil Gaming, thanks again. ^^
See you
