### ISSUE TITLE
WindowHint AutoIconify can't be disabled

### ISSUE THREAD

**Issue by oelison** [andykorth/Pencil.Gaming#44]
Hi,
I have switched to pencil.gaming from openTK because I need the full screen feature.
Every time when the window have lost the focus it disapears from the Monitor, because it is the default in glfw.
To avod this, the call glfwWindowHint(GLFW_AUTO_ICONIFY, GL_FALSE); will fix this.

---Exsamplecode in glfw with c++ (modified example split view demo)---

```
int main(void)
{
    GLFWwindow* window;
    // Initialise GLFW
    if (!glfwInit())
    {
        fprintf(stderr, "Failed to initialize GLFW\n");
        exit(EXIT_FAILURE);
    }
    int MonitCount;
    glfwWindowHint(GLFW_SAMPLES, 4);
    glfwWindowHint(GLFW_AUTO_ICONIFY, GL_FALSE);
    GLFWmonitor* primary = glfwGetPrimaryMonitor();
    GLFWvidmode* AktVidMode = glfwGetVideoMode(primary);
    // Open OpenGL window
    window = glfwCreateWindow(AktVidMode->width, AktVidMode->height, "Split view demo", primary, NULL);
```

---End of exsample code---

But when I try this for pencil.gaming I saw the constant is missing. I added the constant to WindowAttrib (because in glfw it is there and it is correctly enumerated GLFW_AUTO_ICONIFY = 131078 = 0x20006).
So long no problem.
--- Exsamplecode  in pencil.gaming ---

```
Glfw.Init();    
GlfwMonitorPtr[] myMonitors = Glfw.GetMonitors();
Glfw.WindowHint(WindowHint.Samples, 4);
Glfw.WindowHint(WindowHint.ContextVersionMajor, 3);
Glfw.WindowHint(WindowHint.ContextVersionMinor, 3);
Glfw.WindowHint(WindowHint.OpenGLProfile, (int)OpenGLProfile.Compatibility);
Glfw.WindowHint(WindowHint.RefreshRate, 60);
Glfw.WindowHint((WindowHint)WindowAttrib.AutoIconify, 0);

GlfwVidMode AktVidMode = Glfw.GetVideoMode(myMonitors[0]);

window = Glfw.CreateWindow(AktVidMode.Width, AktVidMode.Height, "pencil.gaming test", myMonitors[0], GlfwWindowPtr.Null);
```

---End of exsample code---
This dosen't work and I don't understand why?
May be I will compile an own glfw lib with other default, but this is not preferred from me.
Thanks in advanced for any help.

**Comment by oelison** [comment]
Hi all.
With GLFW 3.2 it is working. So it is no error from Pencil.Gaming.

**Comment by andallas** [comment]
@oelison I forked this and am working on a fix but have run into some issues. What I did was add AutoIconify to the WindowAttrib enum in Glfw3Enum.cs. I ensured it's value matches (0x20006) as well. I also grabbed the latest Glfw dlls for windows 32 and 64 bit (version 3.2.1). Everything builds fine, but I get an Invalid Enum error when attempting to set the AutoIconify window hint.

It sounds like you made it a bit further than I did. Would love a push in the right direction so I can get a pull request put together. Thanks!

**Comment by oelison** [comment]
Hi andallas,
Please have a look at my fork :/oelison/Pencil.Gaming.
This is running under Win 10 with 64bit very well. I have not testetd any other config.
There you can see that I have added the constant 
public enum WindowAttrib
--- code snippet
	public enum WindowAttrib
	{
		Focused = 0x20001,
		Iconified,
		Resizeable,
		Visible,
		Decorated,
		AutoIconify
	}
--- End of code snippet
as you described. You can also see my two new dlls.
Sorry for the reformating of the file Glfw3Enum.cs but it is the coding guidelines here I need to use.
The call with WindowHint must have a cast to WindowHint, because WindowAttrib is not a WindowHint.
Should be a good idea to add the WindowAttrib to the WindowHints, but I'm not sure how to make it without double define the same values and it is at least good code.

**Comment by antonijn** [comment]
Should be fixed on the develop branch.
