### ISSUE TITLE
enum Key.F10 has wrong number

### ISSUE THREAD

**Issue by vbelcik** [andykorth/Pencil.Gaming#45]
in the Pencil.Gaming the Key.F10 = 294
but in the Glfw 3 project:
#define GLFW_KEY_F10                299
This leads to: when hitting F5 I'll actually detect F10 pressed by Pencil.Gaming

Maybe there are also other key codes wrong...

**Comment by andallas** [comment]
I ran into this as well, seems like the function keys are off by 5. Also had issues with some of the keypad keys. Haven't dug in to see what the issue is yet.

**Comment by andallas** [comment]
There, that pull request should fix this, enjoy!

**Comment by andallas** [comment]
@vbelcik Pull request has been merged in, you should be good to go!

**Comment by vbelcik** [comment]
It seems that this bug is fixed. Thanks for fast response.
