### ISSUE TITLE
GLFW 3.0 Bug

### ISSUE THREAD

**Issue by vtester-vi-lwg** [andykorth/Pencil.Gaming#47]
GLFW 3.0 crashes on my system (windows can't be created), which carries over to Pencil.Gaming. The issue is fixed in GLFW 3.2.1 (and my test program is successful in both Pencil and C).

Replacing libglfw.so in Pencil with libglfw.so.3.2 causes pencil to "work" but, due to the difference in GLFW versions between the header and library, likely will break.

Upgrading GLFW should resolve this, although that might be difficult.

**Comment by antonijn** [comment]
Will be fixed along with #40

**Comment by antonijn** [comment]
Fixed in the develop branch.
