### ISSUE TITLE
GetShaderInfoLogs returns an empty string

### ISSUE THREAD

**Issue by courgeon** [andykorth/Pencil.Gaming#48]
Hello

I'm trying to understand why getShaderInfoLog returns an empty string. The shader does not compile (by design) thus linking fails. However, i get no information on why.

I tried compiling the shader with LWJGL (Java & OpenGL) and glGetShaderInfoLog get me a description of the compilation error. 

Any idea ?

```
        int link_status;
        GL.GetProgram(instanceShaderID, ProgramParameter.LinkStatus, out link_status);

        if (link_status == 0)
        {
            Console.Out.WriteLine("Program linking failed...");

            string pinfo;
            GL.GetProgramInfoLog(instanceShaderID, out pinfo);

            // also tried with : string pinfo = GL.GetProgramInfoLog(instanceShaderID);

            if (pinfo.Trim().Length > 0)                
                Console.Out.WriteLine(" >> Program error log : " + pinfo);                
            else
                Console.Out.WriteLine(" >> No further information provided by the OpenGL implementation");
```

JAVA LWJGL output 

> Program linking failed...
> 425 :                 Compilation status : ERROR
>           Compilation status of shader '(...)' : ERROR
>   428 :   ----------------------------------------
>   428 :           Compiler output:
>           0(106) : error C0000: syntax error, unexpected reserved word "return", expecting "::" at token "return"
>   428 :           0(106) : error C0000: syntax error, unexpected reserved word "return", expecting "::" at token "return"
>           0(107) : error C1016: expression type incompatible with function return type
>   428 :           0(107) : error C1016: expression type incompatible with function return type
>           0(104) : error C1108: function "RS" has no statements
>   428 :           0(104) : error C1108: function "RS" has no statements
>   428 :   ----------------------------------------

Pencil Gaming Output

> Program linking failed...
>  No further information provided by the OpenGL implementation`

(hardware and software : Windows 10 - nVidia TitanX)

**Comment by antonijn** [comment]
I'll check it out over the weekend!

**Comment by courgeon** [comment]
Hey, thanks.
Any news ?

**Comment by antonijn** [comment]
This seems to be fixed in the develop branch!

**Comment by courgeon** [comment]
Correct. I confirm that it does work in the develop Branch, thanks
