### ISSUE TITLE
Xamarin Monotouch iOS and Android support?

### ISSUE THREAD

**Issue by blueneogeo** [andykorth/Pencil.Gaming#5]
I'd love to use Pencil.Gaming for iOS and Android openGL programming. Are you planning to support it?

Regards from a fellow dutchie :-) (Weesp)

Christian

**Comment by nvcken** [comment]
Xamarin is now open-source, does it make help for Pencil.Gaming support ios/android ?

**Comment by antonijn** [comment]
Unfortunately I fear that at this point: not going to happen. At least I won't do it.
