### ISSUE TITLE
NV Command List

### ISSUE THREAD

**Issue by courgeon** [andykorth/Pencil.Gaming#50]
Hello, 
I hope there is still someone working on Pencil.Gaming, that's a nice project, but the "issues" section appears to be dead lately.

I was hoping to use the Nvidia Command List extention and wondering if it could be done using Pencil.Gaming. 
As far as I can tell, there is no binding for these extension functions, can someone add them, or at least tell me how to add them myself ?

Best !
M. C

**Comment by andykorth** [comment]
My personal interest has been towards avoiding GL extensions and keeping to the modern gl core, but there's no reason you can't add extensions yourself. 

Take a look at OpenTK, which I believe has a lot of various extensions:
https://github.com/opentk/opentk/tree/develop/src/OpenTK/Graphics

OpenTK looks pretty active at the moment, you might be able to get help using their binding generators even. If you get that working, it can probably be made to plug into pencil pretty easily.

**Comment by courgeon** [comment]
Hi
Ok, fair enough, thanks you the answer. I have a strong experience with OpenGL, but no so much with C# yet. I'll try adding these functions myself. if I eventually  achieve it, I will give the code to you.

On the same topic, the core GL 4.3 functions  "GetProgramResourceIndex" "ShaderStorageBlockBinding" are missing, I added them in my Pencil Gaming local sources. You might want to add them if you ever need to use Shader Storage Blocks.

Just by adding the following code, they work perfectly ;)

In GL.cs : 
```
public static Int32 GetProgramResourceIndex(Int32 program, ProgramInterface programInterface, String name)
{
          return Delegates.glGetProgramResourceIndex((UInt32)program, programInterface, (String)name);
}

public static void ShaderStorageBlockBinding(Int32 program, Int32 location, Int32 binding)
{
            Delegates.glShaderStorageBlockBinding((UInt32)program, location, binding);
}
```

in GLDelegates.cs

```
            [SuppressUnmanagedCodeSecurity()]
            internal delegate Int32 ShaderStorageBlockBinding(UInt32 program, Int32 location, Int32 binding);
            internal static ShaderStorageBlockBinding glShaderStorageBlockBinding;

            [SuppressUnmanagedCodeSecurity()]
            internal delegate Int32 GetProgramResourceIndex(UInt32 program, ProgramInterface programInterface, String name);
            internal static GetProgramResourceIndex glGetProgramResourceIndex;
```            
`
In GlEnum.cs

```
    public enum ProgramInterface : int
    {
        ShaderStorageBlock = ((int)0x92E6)
    }
```

PS : I posted a previous message about shader compilation not providing error log with PrintShaderInfoLog. I still haven't figure that out. Any hint would be greatly appreciated.

Keep up the good work :)
